#!/usr/bin/env python3
"""Flag suspicious folded native stacks; absence of flags is not certification.

Quality warnings are recorded in JSON and return exit status zero. Input/output
errors return status 2. Folded weights are event-period weights when generated by
stackcollapse-perf.pl from perf script output that includes the period field.
"""

import argparse
from collections import Counter
from decimal import Decimal, InvalidOperation
import json
from pathlib import Path
import re
import sys


ADDRESS = re.compile(r"(?<![\w])0x([0-9a-fA-F]+)(?![\w])")
BARE_ADDRESS = re.compile(r"^(?:\[unknown\]\s*)?([0-9a-fA-F]{16})(?:_\[[a-z]\])?$")
WEIGHT = re.compile(r"^[0-9]+(?:\.[0-9]+)?$")


def json_number(value):
    """Keep integer nanosecond totals exact in JSON."""
    if value == value.to_integral_value():
        return int(value)
    return float(value)


def fraction(value, total):
    return float(value / total) if total else None


def canonical(address, bits):
    if address >= (1 << 64):
        return False
    return address < (1 << (bits - 1)) or address >= (1 << 64) - (1 << (bits - 1))


def address_flags(frame):
    addresses = ADDRESS.findall(frame)
    bare = BARE_ADDRESS.fullmatch(frame.strip())
    if bare:
        addresses.append(bare.group(1))
    flags = set()
    for text in addresses:
        lowered = text.lower().lstrip("0")
        # Patterns are warning heuristics, not proof that an address is invalid.
        if re.search(r"(?:dd){3,}|(?:fd){3,}", lowered) or lowered in {"dddd", "fdfd"}:
            flags.add("debug_poison_pattern")
        address = int(text, 16)
        if not canonical(address, 48):
            flags.add("noncanonical_x86_64_48bit")
        if not canonical(address, 57):
            flags.add("noncanonical_x86_64_57bit")
    return flags


def folded_statistics(contents):
    total = Decimal(0)
    weights = Counter()
    counts = Counter()
    frames_total = 0
    unique_frames = set()
    max_depth = 0
    malformed = []
    examples = {}
    records = 0
    for line_number, raw in enumerate(contents.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        try:
            stack, token = line.rsplit(None, 1)
            if not WEIGHT.fullmatch(token):
                raise ValueError("weight is not a nonnegative decimal")
            weight = Decimal(token)
            frames = stack.split(";")
            if not all(frame.strip() for frame in frames):
                raise ValueError("empty frame")
        except (ValueError, InvalidOperation):
            malformed.append(line_number)
            continue
        records += 1
        total += weight
        depth = len(frames)
        max_depth = max(max_depth, depth)
        frames_total += depth
        unique_frames.update(frames)
        flags = set()
        if any("[unknown]" in frame.lower() for frame in frames):
            flags.add("unknown_ancestry")
        if depth >= 127:
            flags.add("depth_at_least_127")
        for frame in frames:
            for flag in address_flags(frame):
                flags.add(flag)
                examples.setdefault(flag, [])
                if frame not in examples[flag] and len(examples[flag]) < 8:
                    examples[flag].append(frame)
        # A stack's weight is counted once per flag, even if many frames match.
        for flag in flags:
            weights[flag] += weight
            counts[flag] += 1
    labels = (
        "unknown_ancestry", "debug_poison_pattern", "noncanonical_x86_64_48bit",
        "noncanonical_x86_64_57bit", "depth_at_least_127",
    )
    return {
        "total_period_weight": json_number(total),
        "folded_records": records,
        "frame_occurrences_unweighted": frames_total,
        "distinct_frame_labels": len(unique_frames),
        "max_depth_including_command_frame": max_depth,
        "malformed_line_count": len(malformed),
        "malformed_line_examples": malformed[:20],
        "flags": {
            label: {
                "records": counts[label],
                "period_weight": json_number(Decimal(weights[label])),
                "fraction_of_total_period_weight": fraction(Decimal(weights[label]), total),
                "example_frames": examples.get(label, []),
            }
            for label in labels
        },
    }


def approximate_samples(text):
    match = re.fullmatch(r"([0-9]+(?:\.[0-9]+)?)([KMG]?)", text.replace(",", "").strip(), re.I)
    if not match:
        return None
    scale = {"": 1, "K": 1000, "M": 1000000, "G": 1000000000}[match.group(2).upper()]
    return float(match.group(1)) * scale


def report_header(contents):
    lost = re.search(r"^\s*#?\s*Total Lost Samples:\s*([\d,]+)", contents, re.M | re.I)
    samples = re.findall(
        r"^\s*#?\s*Samples:\s*([^\r\n]+?)\s+of event\s+['\"]([^'\"]+)['\"]",
        contents, re.M | re.I,
    )
    event_counts = re.findall(
        r"^\s*#?\s*Event count(?:\s*\(approx\.\))?:\s*([\d,]+)", contents, re.M | re.I,
    )
    sample_records = [
        {"event": event, "samples_display": count.strip(), "samples_approx": approximate_samples(count)}
        for count, event in samples
    ]
    return {
        "lost_samples": int(lost.group(1).replace(",", "")) if lost else None,
        "sample_headers": sample_records,
        "event_count_approx_values": [int(value.replace(",", "")) for value in event_counts],
        "complete": bool(lost and samples and event_counts),
    }


def analyze(folded_text, report_text):
    folded = folded_statistics(folded_text)
    header = report_header(report_text)
    reasons = []
    flags = folded["flags"]
    unknown = flags["unknown_ancestry"]["fraction_of_total_period_weight"]
    if unknown is not None and unknown > 0.10:
        reasons.append("More than 10% of folded period weight has at least one [unknown] frame.")
    if flags["debug_poison_pattern"]["records"]:
        reasons.append("Some frame addresses contain repeated debug-memory poison patterns.")
    if flags["noncanonical_x86_64_48bit"]["records"]:
        reasons.append("Some addresses fail the x86-64 48-bit canonical-address heuristic; check the actual architecture/address width.")
    if folded["max_depth_including_command_frame"] >= 127:
        reasons.append("At least one folded stack reaches depth 127 or more, including its command frame.")
    if header["lost_samples"]:
        reasons.append("perf reports lost samples.")
    if not header["complete"]:
        reasons.append("Required perf report header fields are absent; lost samples/event totals cannot all be checked.")
    if len(header["sample_headers"]) > 1 or len(header["event_count_approx_values"]) > 1:
        reasons.append("Multiple event headers are present; ensure folded weights do not mix event types.")
    if folded["malformed_line_count"]:
        reasons.append("Some folded rows could not be parsed and are excluded from totals.")
    if folded["total_period_weight"] <= 0:
        reasons.append("There is no positive folded period weight to assess.")
    events = [item["event"] for item in header["sample_headers"]]
    clock_confirmed = len(events) == 1 and events[0].split(":")[0] in {"cpu-clock", "task-clock"}
    event_total = header["event_count_approx_values"]
    difference = None
    if len(event_total) == 1:
        absolute = folded["total_period_weight"] - event_total[0]
        difference = {
            "folded_minus_report_approx": absolute,
            "relative_to_report_approx": absolute / event_total[0] if event_total[0] else None,
            "interpretation": "Informational only: report count is approximate; filtering or weighting can differ. No equality requirement imposed.",
        }
    return {
        "schema_version": 1,
        "status": "needs_review" if reasons else "review_required",
        "reasons": reasons or ["No configured red flag fired; inspect native call paths and symbols manually before drawing conclusions."],
        "weight_unit": "nanoseconds_of_event_period" if clock_confirmed else "event_period_units_not_confirmed",
        "weight_assumption": "Input was folded from perf script with period weights. Header alone cannot verify the stackcollapse invocation. Weights are not sample counts.",
        "folded": folded,
        "perf_report_header": header,
        "total_comparison": difference,
        "limitations": [
            "This is a heuristic audit, not proof of correct unwinding. Neither status certifies a healthy call graph.",
            "Unknown ancestry fraction counts each matching stack's weight once; it is not unresolved sampled-instruction-pointer fraction.",
            "Address checks assume x86-64-style addresses; LA57, tagged pointers or another architecture require manual interpretation.",
            "Depth includes the command frame and may reflect real recursion, a depth cap or unwind errors.",
            "Zero lost samples does not validate recorded stack ancestry.",
        ],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--folded", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        result = analyze(args.folded.read_text(errors="replace"), args.report.read_text(errors="replace"))
        result["inputs"] = {"folded": str(args.folded.resolve()), "report": str(args.report.resolve())}
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(result, indent=2, sort_keys=True, allow_nan=False) + "\n")
    except (OSError, ValueError) as exc:
        print("stack_health: {}".format(exc), file=sys.stderr)
        return 2
    print("Stack audit: {} ({})".format(result["status"], args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
